spring.application.name=student-blog

# DB from env (set in IntelliJ + Railway)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (na start)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Railway ustawia PORT przy deployu (lokalnie b?dzie 8080)
server.port=${PORT:8080}